[{
            type: "id",
            name: "aerodactyl"
        }, {
            type: "id",
            name: "aggron"
        }, {
            type: "id",
            name: "arbok"
        }, {
            type: "id",
            name: "armaldo"
        }, {
            type: "id",
            name: "cinccino"
        }, {
            type: "id",
            name: "cloyster"
        }, {
            type: "id",
            name: "crobat"
        }, {
            type: "id",
            name: "delcatty"
        }, {
            type: "id",
            name: "donphan"
        }, {
            type: "id",
            name: "drapion"
        }, {
            type: "id",
            name: "drifblim"
        }, {
            type: "id",
            name: "durant"
        }, {
            type: "id",
            name: "escavalier"
        }, {
            type: "id",
            name: "espeon"
        }, {
            type: "id",
            name: "excadrill"
        }, {
            type: "id",
            name: "ferrothorn"
        }, {
            type: "id",
            name: "forretress"
        }, {
            type: "id",
            name: "gengar"
        }, {
            type: "id",
            name: "glalie"
        }, {
            type: "id",
            name: "gligar"
        }, {
            type: "id",
            name: "gliscor"
        }, {
            type: "id",
            name: "golbat"
        }, {
            type: "id",
            name: "golem_alolan"
        }, {
            type: "id",
            name: "gothitelle"
        }, {
            type: "id",
            name: "granbull"
        }, {
            type: "id",
            name: "graveler_alolan"
        }, {
            type: "id",
            name: "grimer"
        }, {
            type: "id",
            name: "haunter"
        }, {
            type: "id",
            name: "klinklang"
        }, {
            type: "id",
            name: "lairon"
        }, {
            type: "id",
            name: "liepard"
        }, {
            type: "id",
            name: "machoke"
        }, {
            type: "id",
            name: "magneton"
        }, {
            type: "id",
            name: "magnezone"
        }, {
            type: "id",
            name: "mantine"
        }, {
            type: "id",
            name: "mightyena"
        }, {
            type: "id",
            name: "misdreavus"
        }, {
            type: "id",
            name: "mismagius"
        }, {
            type: "id",
            name: "muk"
        }, {
            type: "id",
            name: "nidoking"
        }, {
            type: "id",
            name: "noivern"
        }, {
            type: "id",
            name: "probopass"
        }, {
            type: "id",
            name: "purugly"
        }, {
            type: "id",
            name: "qwilfish"
        }, {
            type: "id",
            name: "relicanth"
        }, {
            type: "id",
            name: "rhydon"
        }, {
            type: "id",
            name: "rhyperior"
        }, {
            type: "id",
            name: "skuntank"
        }, {
            type: "id",
            name: "spiritomb"
        }, {
            type: "id",
            name: "steelix"
        }, {
            type: "id",
            name: "swalot"
        }, {
            type: "id",
            name: "venomoth"
        }, {
            type: "id",
            name: "weezing"
        }]