let teamPattern = [{
    include: [{
        filterType: "id",
        values: "persian_alolan"
    }, {
        filterType: "id",
        values: "blastoise"
    }, {
        filterType: "id",
        values: "boldore"
    }, {
        filterType: "id",
        values: "carracosta"
    }, {
        filterType: "id",
        values: "croconaw"
    }, {
        filterType: "id",
        values: "cryogonal"
    }, {
        filterType: "id",
        values: "dewott"
    }, {
        filterType: "id",
        values: "empoleon"
    }, {
        filterType: "id",
        values: "feraligatr"
    }, {
        filterType: "id",
        values: "frogadier"
    }, {
        filterType: "id",
        values: "gabite"
    }, {
        filterType: "id",
        values: "gigalith"
    }, {
        filterType: "id",
        values: "glaceon"
    }, {
        filterType: "id",
        values: "gloom"
    }, {
        filterType: "id",
        values: "greninja"
    }, {
        filterType: "id",
        values: "gyarados"
    }, {
        filterType: "id",
        values: "huntail"
    }, {
        filterType: "id",
        values: "jumpluff"
    }, {
        filterType: "id",
        values: "kingdra"
    }, {
        filterType: "id",
        values: "lanturn"
    }, {
        filterType: "id",
        values: "lucario"
    }, {
        filterType: "id",
        values: "lumineon"
    }, {
        filterType: "id",
        values: "luxio"
    }, {
        filterType: "id",
        values: "luxray"
    }, {
        filterType: "id",
        values: "marshtomp"
    }, {
        filterType: "id",
        values: "masquerain"
    }, {
        filterType: "id",
        values: "metagross"
    }, {
        filterType: "id",
        values: "metang"
    }, {
        filterType: "id",
        values: "nidoqueen"
    }, {
        filterType: "id",
        values: "omanyte"
    }, {
        filterType: "id",
        values: "omastar"
    }, {
        filterType: "id",
        values: "palpitoad"
    }, {
        filterType: "id",
        values: "prinplup"
    }, {
        filterType: "id",
        values: "quagsire"
    }, {
        filterType: "id",
        values: "castform_rainy"
    }, {
        filterType: "id",
        values: "rampardos"
    }, {
        filterType: "id",
        values: "regice"
    }, {
        filterType: "id",
        values: "salamence"
    }, {
        filterType: "id",
        values: "sandslash_alolan"
    }, {
        filterType: "id",
        values: "seadra"
    }, {
        filterType: "id",
        values: "sealeo"
    }, {
        filterType: "id",
        values: "seismitoad"
    }, {
        filterType: "id",
        values: "simipour"
    }, {
        filterType: "id",
        values: "suicune"
    }, {
        filterType: "id",
        values: "swellow"
    }, {
        filterType: "id",
        values: "swoobat"
    }, {
        filterType: "id",
        values: "tangela"
    }, {
        filterType: "id",
        values: "tangrowth"
    }, {
        filterType: "id",
        values: "vaporeon"
    }, {
        filterType: "id",
        values: "wailmer"
    }, {
        filterType: "id",
        values: "wailord"
    }, {
        filterType: "id",
        values: "walrein"
    }, {
        filterType: "id",
        values: "wartortle"
    }]
}, {
    include: [{
        filterType: "id",
        values: "ariados"
    }, {
        filterType: "id",
        values: "bisharp"
    }, {
        filterType: "id",
        values: "blaziken"
    }, {
        filterType: "id",
        values: "braixen"
    }, {
        filterType: "id",
        values: "braviary"
    }, {
        filterType: "id",
        values: "camerupt"
    }, {
        filterType: "id",
        values: "charizard"
    }, {
        filterType: "id",
        values: "charmeleon"
    }, {
        filterType: "id",
        values: "combusken"
    }, {
        filterType: "id",
        values: "crawdaunt"
    }, {
        filterType: "id",
        values: "crustle"
    }, {
        filterType: "id",
        values: "darmanitan"
    }, {
        filterType: "id",
        values: "delphox"
    }, {
        filterType: "id",
        values: "electrode"
    }, {
        filterType: "id",
        values: "emboar"
    }, {
        filterType: "id",
        values: "fletchinder"
    }, {
        filterType: "id",
        values: "heatmor"
    }, {
        filterType: "id",
        values: "kingler"
    }, {
        filterType: "id",
        values: "kricketune"
    }, {
        filterType: "id",
        values: "krookodile"
    }, {
        filterType: "id",
        values: "ledian"
    }, {
        filterType: "id",
        values: "magcargo"
    }, {
        filterType: "id",
        values: "magmar"
    }, {
        filterType: "id",
        values: "magmortar"
    }, {
        filterType: "id",
        values: "octillery"
    }, {
        filterType: "id",
        values: "parasect"
    }, {
        filterType: "id",
        values: "pignite"
    }, {
        filterType: "id",
        values: "porygon_z"
    }, {
        filterType: "id",
        values: "porygon2"
    }, {
        filterType: "id",
        values: "scizor"
    }, {
        filterType: "id",
        values: "scolipede"
    }, {
        filterType: "id",
        values: "seaking"
    }, {
        filterType: "id",
        values: "simisear"
    }, {
        filterType: "id",
        values: "solrock"
    }, {
        filterType: "id",
        values: "sunny Castform"
    }, {
        filterType: "id",
        values: "talonflame"
    }, {
        filterType: "id",
        values: "vileplume"
    }, {
        filterType: "id",
        values: "wormadam_plant"
    }, {
        filterType: "id",
        values: "yanma"
    }
]
}, {
    include: [{
        filterType: "id",
        values: "amoonguss"
    }, {
        filterType: "id",
        values: "ampharos"
    }, {
        filterType: "id",
        values: "archeops"
    }, {
        filterType: "id",
        values: "beartic"
    }, {
        filterType: "id",
        values: "beedrill"
    }, {
        filterType: "id",
        values: "butterfree"
    }, {
        filterType: "id",
        values: "dewgong"
    }, {
        filterType: "id",
        values: "dunsparce"
    }, {
        filterType: "id",
        values: "electabuzz"
    }, {
        filterType: "id",
        values: "electivire"
    }, {
        filterType: "id",
        values: "emolga"
    }, {
        filterType: "id",
        values: "exeggutor"
    }, {
        filterType: "id",
        values: "froslass"
    }, {
        filterType: "id",
        values: "galarian Rapidash"
    }, {
        filterType: "id",
        values: "gallade"
    }, {
        filterType: "id",
        values: "gardevoir"
    }, {
        filterType: "id",
        values: "girafarig"
    }, {
        filterType: "id",
        values: "hypno"
    }, {
        filterType: "id",
        values: "jolteon"
    }, {
        filterType: "id",
        values: "leavanny"
    }, {
        filterType: "id",
        values: "linoone"
    }, {
        filterType: "id",
        values: "lunatone"
    }, {
        filterType: "id",
        values: "manectric"
    }, {
        filterType: "id",
        values: "meowstic_female"
    }, {
        filterType: "id",
        values: "meowstic"
    }, {
        filterType: "id",
        values: "minun"
    }, {
        filterType: "id",
        values: "mothim"
    }, {
        filterType: "id",
        values: "ninetales"
    }, {
        filterType: "id",
        values: "ninjask"
    }, {
        filterType: "id",
        values: "pachirisu"
    }, {
        filterType: "id",
        values: "pelipper"
    }, {
        filterType: "id",
        values: "persian"
    }, {
        filterType: "id",
        values: "plusle"
    }, {
        filterType: "id",
        values: "ponyta"
    }, {
        filterType: "id",
        values: "quilava"
    }, {
        filterType: "id",
        values: "raichu"
    }, {
        filterType: "id",
        values: "rapidash"
    }, {
        filterType: "id",
        values: "shelgon"
    }, {
        filterType: "id",
        values: "cstform_snowy"
    }, {
        filterType: "id",
        values: "sunflora"
    }, {
        filterType: "id",
        values: "swanna"
    }, {
        filterType: "id",
        values: "togekiss"
    }, {
        filterType: "id",
        values: "togetic"
    }, {
        filterType: "id",
        values: "typhlosion"
    }, {
        filterType: "id",
        values: "vespiquen"
    }, {
        filterType: "id",
        values: "zangoose"
    }, {
        filterType: "id",
        values: "zapdos"
    }
]
}, {
    include: [{
        filterType: "id",
        values: "banette"
    }, {
        filterType: "id",
        values: "bayleef"
    }, {
        filterType: "id",
        values: "bellossom"
    }, {
        filterType: "id",
        values: "breloom"
    }, {
        filterType: "id",
        values: "bronzong"
    }, {
        filterType: "id",
        values: "celebi"
    }, {
        filterType: "id",
        values: "chandelure"
    }, {
        filterType: "id",
        values: "chesnaught"
    }, {
        filterType: "id",
        values: "claydol"
    }, {
        filterType: "id",
        values: "cradily"
    }, {
        filterType: "id",
        values: "dusclops"
    }, {
        filterType: "id",
        values: "dustox"
    }, {
        filterType: "id",
        values: "flygon"
    }, {
        filterType: "id",
        values: "garbodor"
    }, {
        filterType: "id",
        values: "golurk"
    }, {
        filterType: "id",
        values: "grimer_alolan"
    }, {
        filterType: "id",
        values: "grotle"
    }, {
        filterType: "id",
        values: "grovyle"
    }, {
        filterType: "id",
        values: "honchkrow"
    }, {
        filterType: "id",
        values: "houndoom"
    }, {
        filterType: "id",
        values: "ivysaur"
    }, {
        filterType: "id",
        values: "leafeon"
    }, {
        filterType: "id",
        values: "lilligant"
    }, {
        filterType: "id",
        values: "ludicolo"
    }, {
        filterType: "id",
        values: "maractus"
    }, {
        filterType: "id",
        values: "mawile"
    }, {
        filterType: "id",
        values: "meganium"
    }, {
        filterType: "id",
        values: "muk_alolan"
    }, {
        filterType: "id",
        values: "munchlax"
    }, {
        filterType: "id",
        values: "murkrow"
    }, {
        filterType: "id",
        values: "quilladin"
    }, {
        filterType: "id",
        values: "raticate_alolan"
    }, {
        filterType: "id",
        values: "roselia"
    }, {
        filterType: "id",
        values: "roserade"
    }, {
        filterType: "id",
        values: "sceptile"
    }, {
        filterType: "id",
        values: "scyther"
    }, {
        filterType: "id",
        values: "serperior"
    }, {
        filterType: "id",
        values: "servine"
    }, {
        filterType: "id",
        values: "simisage"
    }, {
        filterType: "id",
        values: "sneasel"
    }, {
        filterType: "id",
        values: "snorlax"
    }, {
        filterType: "id",
        values: "torterra"
    }, {
        filterType: "id",
        values: "tyranitar"
    }, {
        filterType: "id",
        values: "victreebel"
    }, {
        filterType: "id",
        values: "weavile"
    }, {
        filterType: "id",
        values: "weepinbell"
    }, {
        filterType: "id",
        values: "whimsicott"
    }, {
        filterType: "id",
        values: "wormadam_plant"
    }, {
        filterType: "id",
        values: "xatu"
    }, {
        filterType: "id",
        values: "yanmega"
    }, {
        filterType: "id",
        values: "zebstrika"
    }
]
}, {
    include: [{
        filterType: "id",
        values: "alakazam"
    }, {
        filterType: "id",
        values: "alomomola"
    }, {
        filterType: "id",
        values: "arcanine"
    }, {
        filterType: "id",
        values: "bibarel"
    }, {
        filterType: "id",
        values: "cherrim_sunshine"
    }, {
        filterType: "id",
        values: "corsola"
    }, {
        filterType: "id",
        values: "dragonite"
    }, {
        filterType: "id",
        values: "dugtrio"
    }, {
        filterType: "id",
        values: "fearow"
    }, {
        filterType: "id",
        values: "floatzel"
    }, {
        filterType: "id",
        values: "furret"
    }, {
        filterType: "id",
        values: "golem"
    }, {
        filterType: "id",
        values: "graveler"
    }, {
        filterType: "id",
        values: "hariyama"
    }, {
        filterType: "id",
        values: "hippowdon"
    }, {
        filterType: "id",
        values: "hitmonchan"
    }, {
        filterType: "id",
        values: "hitmontop"
    }, {
        filterType: "id",
        values: "infernape"
    }, {
        filterType: "id",
        values: "kabutops"
    }, {
        filterType: "id",
        values: "kangaskhan"
    }, {
        filterType: "id",
        values: "litleo"
    }, {
        filterType: "id",
        values: "mamoswine"
    }, {
        filterType: "id",
        values: "marowak"
    }, {
        filterType: "id",
        values: "milotic"
    }, {
        filterType: "id",
        values: "monferno"
    }, {
        filterType: "id",
        values: "noctowl"
    }, {
        filterType: "id",
        values: "pidgeot"
    }, {
        filterType: "id",
        values: "piloswine"
    }, {
        filterType: "id",
        values: "pinsir"
    }, {
        filterType: "id",
        values: "porygon"
    }, {
        filterType: "id",
        values: "pyroar"
    }, {
        filterType: "id",
        values: "raichu (Alolan)"
    }, {
        filterType: "id",
        values: "shiftry"
    }, {
        filterType: "id",
        values: "slowbro"
    }, {
        filterType: "id",
        values: "slowking"
    }, {
        filterType: "id",
        values: "staraptor"
    }, {
        filterType: "id",
        values: "sudowoodo"
    }, {
        filterType: "id",
        values: "ursaring"
    }, {
        filterType: "id",
        values: "wormadam_sandy"
    }]
}, {
    include: [{
        filterType: "id",
        values: "aerodactyl"
    }, {
        filterType: "id",
        values: "aggron"
    }, {
        filterType: "id",
        values: "arbok"
    }, {
        filterType: "id",
        values: "armaldo"
    }, {
        filterType: "id",
        values: "cinccino"
    }, {
        filterType: "id",
        values: "cloyster"
    }, {
        filterType: "id",
        values: "crobat"
    }, {
        filterType: "id",
        values: "delcatty"
    }, {
        filterType: "id",
        values: "donphan"
    }, {
        filterType: "id",
        values: "drapion"
    }, {
        filterType: "id",
        values: "drifblim"
    }, {
        filterType: "id",
        values: "durant"
    }, {
        filterType: "id",
        values: "escavalier"
    }, {
        filterType: "id",
        values: "espeon"
    }, {
        filterType: "id",
        values: "excadrill"
    }, {
        filterType: "id",
        values: "ferrothorn"
    }, {
        filterType: "id",
        values: "forretress"
    }, {
        filterType: "id",
        values: "gengar"
    }, {
        filterType: "id",
        values: "glalie"
    }, {
        filterType: "id",
        values: "gligar"
    }, {
        filterType: "id",
        values: "gliscor"
    }, {
        filterType: "id",
        values: "golbat"
    }, {
        filterType: "id",
        values: "golem_alolan"
    }, {
        filterType: "id",
        values: "gothitelle"
    }, {
        filterType: "id",
        values: "granbull"
    }, {
        filterType: "id",
        values: "graveler_alolan"
    }, {
        filterType: "id",
        values: "grimer"
    }, {
        filterType: "id",
        values: "haunter"
    }, {
        filterType: "id",
        values: "klinklang"
    }, {
        filterType: "id",
        values: "lairon"
    }, {
        filterType: "id",
        values: "liepard"
    }, {
        filterType: "id",
        values: "machoke"
    }, {
        filterType: "id",
        values: "magneton"
    }, {
        filterType: "id",
        values: "magnezone"
    }, {
        filterType: "id",
        values: "mantine"
    }, {
        filterType: "id",
        values: "mightyena"
    }, {
        filterType: "id",
        values: "misdreavus"
    }, {
        filterType: "id",
        values: "mismagius"
    }, {
        filterType: "id",
        values: "muk"
    }, {
        filterType: "id",
        values: "nidoking"
    }, {
        filterType: "id",
        values: "noivern"
    }, {
        filterType: "id",
        values: "probopass"
    }, {
        filterType: "id",
        values: "purugly"
    }, {
        filterType: "id",
        values: "qwilfish"
    }, {
        filterType: "id",
        values: "relicanth"
    }, {
        filterType: "id",
        values: "rhydon"
    }, {
        filterType: "id",
        values: "rhyperior"
    }, {
        filterType: "id",
        values: "skuntank"
    }, {
        filterType: "id",
        values: "spiritomb"
    }, {
        filterType: "id",
        values: "steelix"
    }, {
        filterType: "id",
        values: "swalot"
    }, {
        filterType: "id",
        values: "venomoth"
    }, {
        filterType: "id",
        values: "weezing"
    }]
}]

teamPattern = teamPattern.map(slot => {
    return {
        include: [slot.include.reduce((a, b) => {
            if (typeof a.values === "string"){
                a.values = [a.values]
            }
            return {
                filterType: a.filterType,
                values: a.values.concat(b.values)
            }
        })]
    }
})

console.log(JSON.stringify(teamPattern))